controllers:
    resource: ../src/Controller/
    type: attribute


app_logout:
    path: /logout
    methods: GET

profile:
    path: /{username}
    controller: App\Controller\ProfileController::profilePage
    methods: GET

